sonar.projectKey=moreiracruz_erp
sonar.organization=moreiracruz
sonar.host.url=https://sonarcloud.io

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.test.binaries=target/test-classes

sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml,**/target/site/jacoco-aggregate/jacoco.xml
sonar.java.spotbugs.reportPaths=**/target/spotbugsXml.xml
sonar.java.pmd.reportPaths=**/target/pmd.xml
sonar.java.checkstyle.reportPaths=**/target/checkstyle-result.xml

sonar.exclusions=**/target/**,shared/test-support/**,**/*Test*.java,**/*IT.java
sonar.coverage.exclusions=shared/test-support/**,**/adapter/in/web/*Request.java,**/adapter/in/web/*Response.java,**/adapter/out/persistence/**/*JpaEntity.java,**/adapter/out/persistence/**/*JpaRepository.java,**/*Config.java,**/*Configuration.java
